platform :ios, '8.0'

pod 'AFNetworking', '~> 2.6.0'
pod 'GBInfiniteScrollView'
pod 'SDWebImage'
pod 'MONActivityIndicatorView'
pod 'ZXingObjC'
pod 'Fabric'
pod 'Crashlytics'
pod 'MarqueeLabel'
pod 'iOS-Slide-Menu'
pod 'PureLayout'
pod 'GoogleMaps'
pod 'Google/Analytics'
pod 'XCDYouTubeKit', '~> 2.5'
pod 'youtube-ios-player-helper', '~> 0.1.6'

target 'YHFramework' do

end

target 'YHFrameworkTests' do

end

target 'YHFrameworkUITests' do

end

